// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uFnucf8rGPFOwnQh4kjZC1q5JKCrttU',
    appId: '1:604252346484:web:aeb1d7bfbf55c297ee9921',
    messagingSenderId: '604252346484',
    projectId: 'afet-ihbar',
    authDomain: 'afet-ihbar.firebaseapp.com',
    databaseURL: 'https://afet-ihbar-default-rtdb.firebaseio.com',
    storageBucket: 'afet-ihbar.appspot.com',
    measurementId: 'G-5L4HJ6DW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidbYNEDSu5ayK_TztUrl_u5Gcnpl_TTU',
    appId: '1:604252346484:android:c85a99d65eca596aee9921',
    messagingSenderId: '604252346484',
    projectId: 'afet-ihbar',
    databaseURL: 'https://afet-ihbar-default-rtdb.firebaseio.com',
    storageBucket: 'afet-ihbar.appspot.com',
  );
}
